<Project Sdk="Microsoft.NET.Sdk.Web">
	
  <PropertyGroup>
	<Version>7.1.1</Version>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TWS_Foundation</RootNamespace>
	<StartupObject>TWS_Foundation.Program</StartupObject>

  </PropertyGroup>

  <ItemGroup>
    <None Include="Properties\server_properties.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSM.Database.Core" Version="4.4.0" />
    <PackageReference Include="CSM.Foundation.Core" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSM Security\CSM Security.csproj" />
    <ProjectReference Include="..\TWS Business\TWS Business.csproj" />
    <ProjectReference Include="..\TWS Customer\TWS Customer.csproj" />
  </ItemGroup>

</Project>
