// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TWS_Business;

#nullable disable

namespace TWS_Business.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TWS_Business.Entities.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AltStreet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("State")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subdivision")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ZIP")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("TWS_Business.Entities.Approach", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Alternative")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Enterprise")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Personal")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("StatusShadow")
                        .IsUnique();

                    b.ToTable("Approaches", (string)null);
                });

            modelBuilder.Entity("TWS_Business.Entities.Approach_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Alternative")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<long?>("ApproachId")
                        .HasColumnType("bigint");

                    b.Property<string>("EMail")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Enterprise")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Personal")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApproachId");

                    b.HasIndex("StatusId");

                    b.ToTable("Approach_History");
                });

            modelBuilder.Entity("TWS_Business.Entities.Drivers.Driver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ANAM")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateOnly?>("AnamExpiration")
                        .HasColumnType("date");

                    b.Property<long>("CommonShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Common");

                    b.Property<string>("DriverType")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateOnly?>("DrugalcRegistrationDate")
                        .HasColumnType("date");

                    b.Property<long>("EmployeeShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Employee");

                    b.Property<string>("Fast")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateOnly?>("FastExpiration")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LicenseExpiration")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PullnoticeRegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("TWIC")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly?>("TwicExpiration")
                        .HasColumnType("date");

                    b.Property<string>("VISA")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateOnly?>("VisaExpiration")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CommonShadow")
                        .IsUnique();

                    b.HasIndex("EmployeeShadow")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("TWS_Business.Entities.Drivers.DriverExternal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CommonShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Common");

                    b.Property<long>("IdentificationShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Identification");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CommonShadow")
                        .IsUnique();

                    b.HasIndex("IdentificationShadow")
                        .IsUnique();

                    b.ToTable("Drivers_Externals", (string)null);
                });

            modelBuilder.Entity("TWS_Business.Entities.Drivers.Driver_Common", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long>("SituationShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Situation");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("SituationShadow");

                    b.HasIndex("StatusShadow");

                    b.ToTable("Drivers_Commons", (string)null);
                });

            modelBuilder.Entity("TWS_Business.Entities.Employees.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AddressShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Address");

                    b.Property<long?>("ApproachShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Approach");

                    b.Property<string>("CURP")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<long>("DatesShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Dates");

                    b.Property<long>("IdentificationShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Identification");

                    b.Property<string>("NSS")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("RFC")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AddressShadow");

                    b.HasIndex("ApproachShadow");

                    b.HasIndex("DatesShadow")
                        .IsUnique();

                    b.HasIndex("IdentificationShadow")
                        .IsUnique();

                    b.HasIndex("StatusShadow")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TWS_Business.Entities.Employees.Employee_Dates", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("CNAP")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Hire")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IMSS")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Termination")
                        .HasColumnType("date");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employee_Dates");
                });

            modelBuilder.Entity("TWS_Business.Entities.Identification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("StatusShadow")
                        .IsUnique();

                    b.ToTable("Identifications");
                });

            modelBuilder.Entity("TWS_Business.Entities.Insurances.Insurance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("date");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("StatusShadow");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("TWS_Business.Entities.Insurances.Insurance_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("date");

                    b.Property<long?>("InsuranceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceId");

                    b.HasIndex("StatusId");

                    b.ToTable("Insurance_History");
                });

            modelBuilder.Entity("TWS_Business.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Address");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AddressShadow");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusShadow")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TWS_Business.Entities.Maintenances.Maintenance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Anual")
                        .HasColumnType("date");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("Trimestral")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("StatusShadow");

                    b.ToTable("Maintenances");
                });

            modelBuilder.Entity("TWS_Business.Entities.Maintenances.Maintenance_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Anual")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MaintenanceId")
                        .HasColumnType("bigint");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Trimestral")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceId");

                    b.HasIndex("StatusId");

                    b.ToTable("Maintenance_History");
                });

            modelBuilder.Entity("TWS_Business.Entities.Section", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ocupancy")
                        .HasColumnType("int");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("YardShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Yard");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusShadow")
                        .IsUnique();

                    b.HasIndex("YardShadow");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("TWS_Business.Entities.Situation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Situations");
                });

            modelBuilder.Entity("TWS_Business.Entities.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("TWS_Business.Entities.USDOTs.USDOT", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MC")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .IsFixedLength();

                    b.Property<string>("SCAC")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .IsFixedLength();

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("StatusShadow")
                        .IsUnique();

                    b.ToTable("USDOTs");
                });

            modelBuilder.Entity("TWS_Business.Entities.USDOTs.USDOT_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MC")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SCAC")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long?>("USDOTId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("USDOTId");

                    b.ToTable("USDOT_History");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Carrier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Address");

                    b.Property<long>("ApproachShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Approach");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long?>("USDOTShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("USDOT");

                    b.HasKey("Id");

                    b.HasIndex("AddressShadow");

                    b.HasIndex("ApproachShadow");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusShadow")
                        .IsUnique();

                    b.HasIndex("USDOTShadow");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Carrier_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Approach_HistoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CarrierId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SCT_HistoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long?>("USDOT_HistoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Approach_HistoryId");

                    b.HasIndex("CarrierId");

                    b.HasIndex("SCT_HistoryId");

                    b.HasIndex("StatusId");

                    b.HasIndex("USDOT_HistoryId");

                    b.ToTable("Carrier_History");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.LoadType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("LoadTypes");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Manufacturer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Plate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly?>("Expiration")
                        .HasColumnType("date");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("State")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long?>("TrailerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TruckId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StatusShadow");

                    b.HasIndex("TrailerId");

                    b.HasIndex("TruckId");

                    b.ToTable("Plates");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Plate_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly?>("Expiration")
                        .HasColumnType("date");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PlateId")
                        .HasColumnType("bigint");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlateId");

                    b.HasIndex("StatusId");

                    b.ToTable("Plate_History");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.SCT", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("StatusShadow");

                    b.ToTable("SCTs");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.SCT_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long?>("SCTId")
                        .HasColumnType("bigint");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("SCTId");

                    b.ToTable("SCT_History");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.Trailer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CarrierShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Carrier");

                    b.Property<long>("CommonShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Common");

                    b.Property<long?>("MaintenanceShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Maintenance");

                    b.Property<long?>("ModelShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Model");

                    b.Property<long?>("SCTShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("SCT");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CarrierShadow");

                    b.HasIndex("CommonShadow")
                        .IsUnique();

                    b.HasIndex("MaintenanceShadow");

                    b.HasIndex("ModelShadow");

                    b.HasIndex("SCTShadow");

                    b.ToTable("Trailers");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.TrailerExternal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CommonShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Common");

                    b.Property<string>("MxPlate")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UsaPlate")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("CommonShadow")
                        .IsUnique();

                    b.ToTable("Trailers_Externals", (string)null);
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.Trailer_Class", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Trailer_Classes");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.Trailer_Common", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Economic")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long?>("LocationShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Location");

                    b.Property<long?>("SituationShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Situation");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long?>("TypeShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("LocationShadow");

                    b.HasIndex("SituationShadow");

                    b.HasIndex("StatusShadow");

                    b.HasIndex("TypeShadow");

                    b.ToTable("Trailers_Commons", (string)null);
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.Trailer_Type", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Class");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ClassShadow");

                    b.HasIndex("StatusShadow");

                    b.ToTable("Trailer_Types", (string)null);
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trucks.Truck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CarrierShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Carrier");

                    b.Property<long>("CommonShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Common");

                    b.Property<long?>("InsuranceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaintenanceShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Maintenance");

                    b.Property<long>("ModelShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Model");

                    b.Property<string>("Motor")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long?>("SCTShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("SCT");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("CarrierShadow");

                    b.HasIndex("CommonShadow")
                        .IsUnique();

                    b.HasIndex("InsuranceId");

                    b.HasIndex("MaintenanceShadow");

                    b.HasIndex("ModelShadow");

                    b.HasIndex("SCTShadow");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trucks.TruckExternal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CommonShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Common");

                    b.Property<string>("MxPlate")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UsaPlate")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("CommonShadow")
                        .IsUnique();

                    b.ToTable("Trucks_Externals", (string)null);
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trucks.Truck_Common", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Economic")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long?>("LocationShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Location");

                    b.Property<long?>("SituationShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Situation");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("LocationShadow");

                    b.HasIndex("SituationShadow");

                    b.HasIndex("StatusShadow");

                    b.ToTable("TrucksCommons");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trucks.Truck_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Economic")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long?>("Insurance_HistoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Maintenance_HistoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ManufacturerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Motor")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TruckId")
                        .HasColumnType("bigint");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long?>("VehiculeModelId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Insurance_HistoryId");

                    b.HasIndex("Maintenance_HistoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("TruckId");

                    b.HasIndex("VehiculeModelId");

                    b.ToTable("Truck_History");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.VehiculeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("ManufacturerShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StatusShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("Year")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerShadow");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusShadow");

                    b.ToTable("Vehicule_Models", (string)null);
                });

            modelBuilder.Entity("TWS_Business.Entities.Waypoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Altitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<long>("LocationShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Location");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("LocationShadow")
                        .IsUnique();

                    b.ToTable("Waypoints");
                });

            modelBuilder.Entity("TWS_Business.Entities.YardLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Damage")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("DriverShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Driver");

                    b.Property<bool>("Entry")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Evidence")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FromTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("GuardShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Guard");

                    b.Property<long>("LoadTypeShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("LoadType");

                    b.Property<string>("Seal")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SealAlt")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("SectionShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Section");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long?>("TrailerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TrailerShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Trailer");

                    b.Property<long?>("TruckId")
                        .HasColumnType("bigint");

                    b.Property<long>("TruckShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Truck");

                    b.HasKey("Id");

                    b.HasIndex("DriverShadow")
                        .IsUnique();

                    b.HasIndex("GuardShadow")
                        .IsUnique();

                    b.HasIndex("LoadTypeShadow");

                    b.HasIndex("SectionShadow");

                    b.HasIndex("TrailerId");

                    b.HasIndex("TrailerShadow")
                        .IsUnique()
                        .HasFilter("[Trailer] IS NOT NULL");

                    b.HasIndex("TruckId");

                    b.HasIndex("TruckShadow")
                        .IsUnique();

                    b.ToTable("Yard_Logs", (string)null);
                });

            modelBuilder.Entity("TWS_Business.Entities.Approach", b =>
                {
                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.Approach", "StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Approach_History", b =>
                {
                    b.HasOne("TWS_Business.Entities.Approach", null)
                        .WithMany("History")
                        .HasForeignKey("ApproachId");

                    b.HasOne("TWS_Business.Entities.Status", null)
                        .WithMany("ApproachesHistories")
                        .HasForeignKey("StatusId");
                });

            modelBuilder.Entity("TWS_Business.Entities.Drivers.Driver", b =>
                {
                    b.HasOne("TWS_Business.Entities.Drivers.Driver_Common", "Common")
                        .WithOne("Internal")
                        .HasForeignKey("TWS_Business.Entities.Drivers.Driver", "CommonShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Employees.Employee", "Employee")
                        .WithOne("Driver")
                        .HasForeignKey("TWS_Business.Entities.Drivers.Driver", "EmployeeShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Common");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TWS_Business.Entities.Drivers.DriverExternal", b =>
                {
                    b.HasOne("TWS_Business.Entities.Drivers.Driver_Common", "Common")
                        .WithOne("External")
                        .HasForeignKey("TWS_Business.Entities.Drivers.DriverExternal", "CommonShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Identification", "Identification")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.Drivers.DriverExternal", "IdentificationShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Common");

                    b.Navigation("Identification");
                });

            modelBuilder.Entity("TWS_Business.Entities.Drivers.Driver_Common", b =>
                {
                    b.HasOne("TWS_Business.Entities.Situation", "Situation")
                        .WithMany("Drivers")
                        .HasForeignKey("SituationShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithMany("Drivers")
                        .HasForeignKey("StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Situation");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Employees.Employee", b =>
                {
                    b.HasOne("TWS_Business.Entities.Address", "Address")
                        .WithMany("Employees")
                        .HasForeignKey("AddressShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TWS_Business.Entities.Approach", "Approach")
                        .WithMany("Employees")
                        .HasForeignKey("ApproachShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TWS_Business.Entities.Employees.Employee_Dates", "Dates")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.Employees.Employee", "DatesShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Identification", "Identification")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.Employees.Employee", "IdentificationShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.Employees.Employee", "StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Approach");

                    b.Navigation("Dates");

                    b.Navigation("Identification");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Identification", b =>
                {
                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.Identification", "StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Insurances.Insurance", b =>
                {
                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithMany("Insurances")
                        .HasForeignKey("StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Insurances.Insurance_History", b =>
                {
                    b.HasOne("TWS_Business.Entities.Insurances.Insurance", null)
                        .WithMany("History")
                        .HasForeignKey("InsuranceId");

                    b.HasOne("TWS_Business.Entities.Status", null)
                        .WithMany("InsurancesHistories")
                        .HasForeignKey("StatusId");
                });

            modelBuilder.Entity("TWS_Business.Entities.Location", b =>
                {
                    b.HasOne("TWS_Business.Entities.Address", "Address")
                        .WithMany("Locations")
                        .HasForeignKey("AddressShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.Location", "StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Maintenances.Maintenance", b =>
                {
                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithMany("Maintenances")
                        .HasForeignKey("StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Maintenances.Maintenance_History", b =>
                {
                    b.HasOne("TWS_Business.Entities.Maintenances.Maintenance", null)
                        .WithMany("History")
                        .HasForeignKey("MaintenanceId");

                    b.HasOne("TWS_Business.Entities.Status", null)
                        .WithMany("MaintenancesHistories")
                        .HasForeignKey("StatusId");
                });

            modelBuilder.Entity("TWS_Business.Entities.Section", b =>
                {
                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.Section", "StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Location", "Yard")
                        .WithMany("Sections")
                        .HasForeignKey("YardShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Yard");
                });

            modelBuilder.Entity("TWS_Business.Entities.USDOTs.USDOT", b =>
                {
                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.USDOTs.USDOT", "StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.USDOTs.USDOT_History", b =>
                {
                    b.HasOne("TWS_Business.Entities.USDOTs.USDOT", null)
                        .WithMany("History")
                        .HasForeignKey("USDOTId");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Carrier", b =>
                {
                    b.HasOne("TWS_Business.Entities.Address", "Address")
                        .WithMany("Carriers")
                        .HasForeignKey("AddressShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Approach", "Approach")
                        .WithMany("Carriers")
                        .HasForeignKey("ApproachShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.Vehicules.Carrier", "StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.USDOTs.USDOT", "USDOT")
                        .WithMany("Carriers")
                        .HasForeignKey("USDOTShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("Approach");

                    b.Navigation("Status");

                    b.Navigation("USDOT");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Carrier_History", b =>
                {
                    b.HasOne("TWS_Business.Entities.Address", null)
                        .WithMany("CarriersHistories")
                        .HasForeignKey("AddressId");

                    b.HasOne("TWS_Business.Entities.Approach_History", null)
                        .WithMany("CarriersHistories")
                        .HasForeignKey("Approach_HistoryId");

                    b.HasOne("TWS_Business.Entities.Vehicules.Carrier", null)
                        .WithMany("History")
                        .HasForeignKey("CarrierId");

                    b.HasOne("TWS_Business.Entities.Vehicules.SCT_History", null)
                        .WithMany("CarriersH")
                        .HasForeignKey("SCT_HistoryId");

                    b.HasOne("TWS_Business.Entities.Status", null)
                        .WithMany("CarriersHistories")
                        .HasForeignKey("StatusId");

                    b.HasOne("TWS_Business.Entities.USDOTs.USDOT_History", null)
                        .WithMany("CarriersHistories")
                        .HasForeignKey("USDOT_HistoryId");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Plate", b =>
                {
                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithMany("Plates")
                        .HasForeignKey("StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Vehicules.Trailers.Trailer", null)
                        .WithMany("Plates")
                        .HasForeignKey("TrailerId");

                    b.HasOne("TWS_Business.Entities.Vehicules.Trucks.Truck", null)
                        .WithMany("Plates")
                        .HasForeignKey("TruckId");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Plate_History", b =>
                {
                    b.HasOne("TWS_Business.Entities.Vehicules.Plate", null)
                        .WithMany("History")
                        .HasForeignKey("PlateId");

                    b.HasOne("TWS_Business.Entities.Status", null)
                        .WithMany("PlatesHistories")
                        .HasForeignKey("StatusId");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.SCT", b =>
                {
                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithMany("SCTs")
                        .HasForeignKey("StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.SCT_History", b =>
                {
                    b.HasOne("TWS_Business.Entities.Vehicules.SCT", null)
                        .WithMany("History")
                        .HasForeignKey("SCTId");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.Trailer", b =>
                {
                    b.HasOne("TWS_Business.Entities.Vehicules.Carrier", "Carrier")
                        .WithMany("Trailers")
                        .HasForeignKey("CarrierShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Vehicules.Trailers.Trailer_Common", "Common")
                        .WithOne("Internal")
                        .HasForeignKey("TWS_Business.Entities.Vehicules.Trailers.Trailer", "CommonShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Maintenances.Maintenance", "Maintenance")
                        .WithMany("Trailers")
                        .HasForeignKey("MaintenanceShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TWS_Business.Entities.Vehicules.VehiculeModel", "Model")
                        .WithMany("Trailers")
                        .HasForeignKey("ModelShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TWS_Business.Entities.Vehicules.SCT", "SCT")
                        .WithMany("Trailers")
                        .HasForeignKey("SCTShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Carrier");

                    b.Navigation("Common");

                    b.Navigation("Maintenance");

                    b.Navigation("Model");

                    b.Navigation("SCT");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.TrailerExternal", b =>
                {
                    b.HasOne("TWS_Business.Entities.Vehicules.Trailers.Trailer_Common", "Common")
                        .WithOne("External")
                        .HasForeignKey("TWS_Business.Entities.Vehicules.Trailers.TrailerExternal", "CommonShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Common");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.Trailer_Common", b =>
                {
                    b.HasOne("TWS_Business.Entities.Location", "Location")
                        .WithMany("Trailers")
                        .HasForeignKey("LocationShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TWS_Business.Entities.Situation", "Situation")
                        .WithMany("Trailers")
                        .HasForeignKey("SituationShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithMany("Trailers")
                        .HasForeignKey("StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Vehicules.Trailers.Trailer_Type", "Type")
                        .WithMany("Trailers")
                        .HasForeignKey("TypeShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");

                    b.Navigation("Situation");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.Trailer_Type", b =>
                {
                    b.HasOne("TWS_Business.Entities.Vehicules.Trailers.Trailer_Class", "Class")
                        .WithMany("TrailerTypes")
                        .HasForeignKey("ClassShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithMany("TrailerTypes")
                        .HasForeignKey("StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trucks.Truck", b =>
                {
                    b.HasOne("TWS_Business.Entities.Vehicules.Carrier", "Carrier")
                        .WithMany("Trucks")
                        .HasForeignKey("CarrierShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Vehicules.Trucks.Truck_Common", "Common")
                        .WithOne("Internal")
                        .HasForeignKey("TWS_Business.Entities.Vehicules.Trucks.Truck", "CommonShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Insurances.Insurance", null)
                        .WithMany("Trucks")
                        .HasForeignKey("InsuranceId");

                    b.HasOne("TWS_Business.Entities.Maintenances.Maintenance", "Maintenance")
                        .WithMany("Trucks")
                        .HasForeignKey("MaintenanceShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TWS_Business.Entities.Vehicules.VehiculeModel", "Model")
                        .WithMany("Trucks")
                        .HasForeignKey("ModelShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Vehicules.SCT", "SCT")
                        .WithMany("Trucks")
                        .HasForeignKey("SCTShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Carrier");

                    b.Navigation("Common");

                    b.Navigation("Maintenance");

                    b.Navigation("Model");

                    b.Navigation("SCT");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trucks.TruckExternal", b =>
                {
                    b.HasOne("TWS_Business.Entities.Vehicules.Trucks.Truck_Common", "Common")
                        .WithOne("External")
                        .HasForeignKey("TWS_Business.Entities.Vehicules.Trucks.TruckExternal", "CommonShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Common");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trucks.Truck_Common", b =>
                {
                    b.HasOne("TWS_Business.Entities.Location", "Location")
                        .WithMany("Trucks")
                        .HasForeignKey("LocationShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TWS_Business.Entities.Situation", "Situation")
                        .WithMany("Trucks")
                        .HasForeignKey("SituationShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithMany("Trucks")
                        .HasForeignKey("StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Situation");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trucks.Truck_History", b =>
                {
                    b.HasOne("TWS_Business.Entities.Insurances.Insurance_History", null)
                        .WithMany("TrucksHistories")
                        .HasForeignKey("Insurance_HistoryId");

                    b.HasOne("TWS_Business.Entities.Maintenances.Maintenance_History", null)
                        .WithMany("TrucksHistories")
                        .HasForeignKey("Maintenance_HistoryId");

                    b.HasOne("TWS_Business.Entities.Vehicules.Manufacturer", null)
                        .WithMany("TrucksHistories")
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("TWS_Business.Entities.Vehicules.Trucks.Truck", null)
                        .WithMany("History")
                        .HasForeignKey("TruckId");

                    b.HasOne("TWS_Business.Entities.Vehicules.VehiculeModel", null)
                        .WithMany("TrucksHistories")
                        .HasForeignKey("VehiculeModelId");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.VehiculeModel", b =>
                {
                    b.HasOne("TWS_Business.Entities.Vehicules.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Status", "Status")
                        .WithMany("Models")
                        .HasForeignKey("StatusShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TWS_Business.Entities.Waypoint", b =>
                {
                    b.HasOne("TWS_Business.Entities.Location", "Location")
                        .WithOne("Waypoint")
                        .HasForeignKey("TWS_Business.Entities.Waypoint", "LocationShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TWS_Business.Entities.YardLog", b =>
                {
                    b.HasOne("TWS_Business.Entities.Drivers.Driver_Common", "Driver")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.YardLog", "DriverShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Employees.Employee", "Guard")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.YardLog", "GuardShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Vehicules.LoadType", "LoadType")
                        .WithMany("YardLogs")
                        .HasForeignKey("LoadTypeShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Section", "Section")
                        .WithMany("YardLogs")
                        .HasForeignKey("SectionShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TWS_Business.Entities.Vehicules.Trailers.Trailer", null)
                        .WithMany("YardLogs")
                        .HasForeignKey("TrailerId");

                    b.HasOne("TWS_Business.Entities.Vehicules.Trailers.Trailer_Common", "Trailer")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.YardLog", "TrailerShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TWS_Business.Entities.Vehicules.Trucks.Truck", null)
                        .WithMany("YardLogs")
                        .HasForeignKey("TruckId");

                    b.HasOne("TWS_Business.Entities.Vehicules.Trucks.Truck_Common", "Truck")
                        .WithOne()
                        .HasForeignKey("TWS_Business.Entities.YardLog", "TruckShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Guard");

                    b.Navigation("LoadType");

                    b.Navigation("Section");

                    b.Navigation("Trailer");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("TWS_Business.Entities.Address", b =>
                {
                    b.Navigation("Carriers");

                    b.Navigation("CarriersHistories");

                    b.Navigation("Employees");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("TWS_Business.Entities.Approach", b =>
                {
                    b.Navigation("Carriers");

                    b.Navigation("Employees");

                    b.Navigation("History");
                });

            modelBuilder.Entity("TWS_Business.Entities.Approach_History", b =>
                {
                    b.Navigation("CarriersHistories");
                });

            modelBuilder.Entity("TWS_Business.Entities.Drivers.Driver_Common", b =>
                {
                    b.Navigation("External");

                    b.Navigation("Internal");
                });

            modelBuilder.Entity("TWS_Business.Entities.Employees.Employee", b =>
                {
                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TWS_Business.Entities.Insurances.Insurance", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("TWS_Business.Entities.Insurances.Insurance_History", b =>
                {
                    b.Navigation("TrucksHistories");
                });

            modelBuilder.Entity("TWS_Business.Entities.Location", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Trailers");

                    b.Navigation("Trucks");

                    b.Navigation("Waypoint");
                });

            modelBuilder.Entity("TWS_Business.Entities.Maintenances.Maintenance", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Trailers");

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("TWS_Business.Entities.Maintenances.Maintenance_History", b =>
                {
                    b.Navigation("TrucksHistories");
                });

            modelBuilder.Entity("TWS_Business.Entities.Section", b =>
                {
                    b.Navigation("YardLogs");
                });

            modelBuilder.Entity("TWS_Business.Entities.Situation", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Trailers");

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("TWS_Business.Entities.Status", b =>
                {
                    b.Navigation("ApproachesHistories");

                    b.Navigation("CarriersHistories");

                    b.Navigation("Drivers");

                    b.Navigation("Insurances");

                    b.Navigation("InsurancesHistories");

                    b.Navigation("Maintenances");

                    b.Navigation("MaintenancesHistories");

                    b.Navigation("Models");

                    b.Navigation("Plates");

                    b.Navigation("PlatesHistories");

                    b.Navigation("SCTs");

                    b.Navigation("TrailerTypes");

                    b.Navigation("Trailers");

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("TWS_Business.Entities.USDOTs.USDOT", b =>
                {
                    b.Navigation("Carriers");

                    b.Navigation("History");
                });

            modelBuilder.Entity("TWS_Business.Entities.USDOTs.USDOT_History", b =>
                {
                    b.Navigation("CarriersHistories");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Carrier", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Trailers");

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.LoadType", b =>
                {
                    b.Navigation("YardLogs");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Manufacturer", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("TrucksHistories");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Plate", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.SCT", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Trailers");

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.SCT_History", b =>
                {
                    b.Navigation("CarriersH");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.Trailer", b =>
                {
                    b.Navigation("Plates");

                    b.Navigation("YardLogs");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.Trailer_Class", b =>
                {
                    b.Navigation("TrailerTypes");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.Trailer_Common", b =>
                {
                    b.Navigation("External");

                    b.Navigation("Internal");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trailers.Trailer_Type", b =>
                {
                    b.Navigation("Trailers");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trucks.Truck", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Plates");

                    b.Navigation("YardLogs");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.Trucks.Truck_Common", b =>
                {
                    b.Navigation("External");

                    b.Navigation("Internal");
                });

            modelBuilder.Entity("TWS_Business.Entities.Vehicules.VehiculeModel", b =>
                {
                    b.Navigation("Trailers");

                    b.Navigation("Trucks");

                    b.Navigation("TrucksHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
