name: tws_foundation_client
description: A client package for [TWS Foundation] server.
version: 2.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:

  csm_foundation_services:
    git:
      url: https://github.com/RMotive/csm_foundation_services
      ref: main

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
