name: tws_foundation_client
description: A client package for [TWS Foundation] server.
version: 6.1.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:

  csm_client_testing:
      git:
        url: https://github.com/Cosmos-CSM/csm_client
        path: csm_client_testing
        ref: dart_fixes

  csm_client_core:
    git:
      url: https://github.com/Cosmos-CSM/csm_client
      path: csm_client_core
      ref: dart_fixes



dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
