name: tws_foundation_client
description: A client package for [TWS Foundation] server.
version: 5.1.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:

  csm_client:
    git:
      url: https://github.com/RMotive/csm_client
      ref: main

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
