using System.Reflection;
using System.Text.Json;

using CSM_Foundation.Database.Bases;
using CSM_Foundation.Database.Entity;
using CSM_Foundation.Database.Models;
using CSM_Foundation.Server.Enumerators;
using CSM_Foundation.Server.Managers;

using Microsoft.EntityFrameworkCore;

namespace CSM_Foundation.Database.Utilitites;
public class DatabaseUtilities {
    const string DirectoryName = ".Connection";
    const string QualityPrefix = "quality";
    const string DevelopmentPrefix = "development";
    const string ProductionPrefix = "production";


    /// <summary>
    ///     Connection file name template for Quality environment variable.
    /// </summary>
    const string Q_CONNTION_TMPLATE = "Q_{0}.Connection";

    /// <summary>
    ///     Fetches and loads through IO functionallities for private file based secret
    ///     connection properties for DataDatabasess connections handlers. 
    ///     Then build it and validate it to generate a Model.
    ///     
    ///     RECOMMENDED: Check the parameter documentation to ensure the correct use.
    /// </summary>
    /// <param name="cp"> 
    ///     Automatically gets the path of the method caller through execution-time assemblies access
    ///     attribute decorator, this is correctly calculated when the method is called
    ///     directly in the DataDatabases context class that is generated by the EF CLI tools when 
    ///     migrated a database configuration, otherwise can struggle with the correct project 
    ///     file leveling generation. 
    ///     In that kind of cases this parameter can be overwritten by the caller to inject
    ///     the correct dataDatabases project root path.
    /// </param>
    /// <returns>
    ///     <see cref="ConnectionOptions"/>: The dataDatabases connection properties gathered and retrieved from the found private properties file.
    /// </returns>
    /// <exception cref="Exception">
    ///     When something gone wrong during the IO connection properties gather operation.
    /// </exception>
    public static ConnectionOptions Retrieve(string DatabaseSign) {
        string wd = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!;

        string prefix = EnvironmentManager.Mode switch {
            ServerEnvironments.development => DevelopmentPrefix,
            ServerEnvironments.quality => QualityPrefix,
            ServerEnvironments.production => ProductionPrefix,
            _ => DevelopmentPrefix,
        };
        string fn = $"{prefix}.connection.json";

        if (wd is null) {
            throw new ArgumentNullException(wd);
        }

        string tp = $"{wd}\\{DatabaseSign.ToUpper()}{DirectoryName}";
        string? cpd = Directory.GetDirectories(wd)
            .Where(i => i == tp)
            .FirstOrDefault()
            ?? throw new DirectoryNotFoundException($"{tp} not found in the system");

        string tfn = $"{tp}\\{fn}";

        string[] cfs = Directory.GetFiles(cpd);
        string cpfi = cfs
            .Where(i => i == tfn)
            .FirstOrDefault()
            ?? throw new FileNotFoundException($"{tfn} not found in the system");

        using FileStream pfs = new(cpfi, FileMode.Open, FileAccess.Read, FileShare.Read);
        ConnectionOptions? m = JsonSerializer.Deserialize<ConnectionOptions>(pfs);
        pfs.Dispose();

        return m is null ? throw new Exception() : m;
    }

    /// <summary>
    ///     Sanitizes the entity relations to ensure that the relations are correctly tracked from the database and avoid the creation of relation entities wrongly given through the main entity.
    /// </summary>
    /// <typeparam name="TEntity">
    ///     Type of the Main Entity to be sanitized.
    /// </typeparam>
    /// <param name="database">
    ///     Database context handler for Entity to be sanitized.
    /// </param>
    /// <param name="entity">
    ///     Entity instance to be sanitized
    /// </param>
    /// <returns></returns>
    /// <exception cref="InvalidOperationException">
    ///     Thrown when the dbSet couldn't be found for the relation entity.
    ///     Thrown when a relation Entity is being tried to be created automatically.
    ///     Thrown when the relation isn´t a IEntity implementation neither a Collection of IEntity.
    /// </exception>
    /// <exception cref="Exception">
    ///     Thrown when the relation entity couldn't be found in the database.
    /// </exception>
    public static TEntity SanitizeEntity<TEntity>(DbContext database, TEntity entity) {
        if (entity == null) {
            return entity;
        }

        IEnumerable<PropertyInfo> relationsProperties = entity.GetType().GetProperties().Where(
                (pi) => pi.GetCustomAttribute<RelationAttribute>() != null
            );

        foreach (PropertyInfo relationProperty in relationsProperties) {
            Type relationType = relationProperty.PropertyType;
            object? relationValue = relationProperty.GetValue(entity);
            if (relationValue is null) {
                continue;
            }

            MethodInfo dbContextSetMethod = typeof(DbContext)
                .GetMethods()
                .Where(
                    m => m.Name == nameof(DbContext.Set) && m.IsGenericMethod && m.GetGenericArguments().Length == 1
                )
                .FirstOrDefault()?.MakeGenericMethod(relationType)
                ?? throw new Exception($"Unreasonable problem, DbContext doesn´t have longer the Set method to build DbSet generically");

            object? rawDbSet = dbContextSetMethod.Invoke(database, null)
                ?? throw new Exception($"Unable to locate DbSet of Type ({relationType.Name}) for Database ({database.GetType().Name})");
            IQueryable<IEntity> dbSet = rawDbSet as IQueryable<IEntity> 
                ?? throw new Exception();

            if (relationValue is IEntity relationEntity) {
                if (relationEntity.Id <= 0) {
                    throw new Exception($"Dependencies aren't allowed to be auto-created on main Entity creation, you need to create the Dependency first in its corresponding [Depot]");
                }

                IEntity tmpDependency = dbSet.Where(
                    i => i.Id == relationEntity.Id
                    ).FirstOrDefault()
                    ?? throw new Exception($"Couldn't find pointing relation of Type ({relationType}) with Id ({relationEntity.Id})");

                relationProperty.SetValue(entity, tmpDependency);
            } else if (relationValue is ICollection<IEntity> relatedEntities) {

                List<IEntity> trackedCollection = [];
                foreach (IEntity relatedEntity in relatedEntities) {

                    IEntity tmpDependency = dbSet.Where(
                        i => i.Id == relatedEntity.Id
                        ).FirstOrDefault()
                        ?? throw new Exception($"Couldn't find pointing relation of Type ({relationType}) with Id ({relatedEntity.Id})");

                    trackedCollection.Add(tmpDependency);
                }

                relationProperty.SetValue(entity, trackedCollection);
            } else {
                throw new InvalidOperationException($"The relation isn't an IEntity implementation neither a Collection of IEntity");
            }
        }
        return entity;
    }

    /// <summary>
    ///     Creates a new <typeparamref name="TDatabase"/> instance for quality/testing purposes, getting the connection options file from 
    ///     the run settings environment variables required.
    /// </summary>
    /// <typeparam name="TDatabase">
    ///     Database context handler type.
    /// </typeparam>
    /// <param name="Sign">
    ///     Specific database connection sign for identification.
    /// </param>
    /// <returns>
    ///     An instance of <typeparamref name="TDatabase"/>.
    /// </returns>
    /// <exception cref="Exception">
    ///     <list type="bullet">
    ///         <item> Thrown when envrionment variable couldn't be found </item>
    ///         <item> Thrown when the file specified doesn't match the Connection Options format </item>
    ///         <item> Thrown when the Activator couldn't create correctly the instance of the database context </item>
    ///     </list>
    /// </exception>
    internal static TDatabase Construct<TDatabase>(string Sign)
        where TDatabase : BDatabase_SQLServer<TDatabase> {

        string connectionVariable = string.Format(Q_CONNTION_TMPLATE, Sign);

        string connectionPath = Environment.GetEnvironmentVariable(connectionVariable)
            ?? throw new Exception($"Unable to run tests for {typeof(TDatabase).FullName}, due to couldn't be found Connection file path (Make sure the environment variable [{connectionVariable}] is set or configured at the .runsettings tests context)");

        using FileStream fileReader = new(connectionPath, FileMode.Open, FileAccess.Read);

        ConnectionOptions connection = JsonSerializer.Deserialize<ConnectionOptions>(fileReader)
            ?? throw new Exception($"File ({connectionPath}) doesn't contain the correct format for (ConnectionOptions)");

        TDatabase Database = (TDatabase?)Activator.CreateInstance(typeof(TDatabase), connection)
            ?? throw new Exception($"Unable to create ({typeof(TDatabase).FullName}) instance with the ConnectionOptions[{connectionPath}]");

        return Database;
    }
}
