use [TWS Security];

insert into Features(Name, Description) 
	values('Quality', 'Specifies that the user is for and only quality testing purposes, 
	EXTREMELY CARE WITH THIS because all entities generated by users with this feature will be rollbacked 
	after the server respond');

insert into Permits(Name, Description, Solution)
	values('Quality', 'Quality feature purposes for TWS Administration solution', 1); -- Check the given solution matches with the actual id solution for [TWSAdministration] --


insert into Accounts_Permits(Account, Permit)
	values(3112, 4); -- Check the given Account id is the correct account id to be used as a quality account --