// <auto-generated />
using System;
using CSM_Security;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSM_Security.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20250327035759_[03.26-2025] Added default timestamp value as GETUTCDATE gathered from sql instance time management")]
    partial class _03262025AddeddefaulttimestampvalueasGETUTCDATEgatheredfromsqlinstancetimemanagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Accounts_Permits", b =>
                {
                    b.Property<long>("Account")
                        .HasColumnType("bigint");

                    b.Property<long>("Permit")
                        .HasColumnType("bigint");

                    b.HasKey("Account", "Permit");

                    b.HasIndex("Permit");

                    b.ToTable("Accounts_Permits");
                });

            modelBuilder.Entity("Accounts_Profiles", b =>
                {
                    b.Property<long>("Account")
                        .HasColumnType("bigint");

                    b.Property<long>("Profile")
                        .HasColumnType("bigint");

                    b.HasKey("Account", "Profile");

                    b.HasIndex("Profile");

                    b.ToTable("Accounts_Profiles");
                });

            modelBuilder.Entity("CSM_Security.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContactShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Contact");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Wildcard")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ContactShadow")
                        .IsUnique();

                    b.HasIndex("User")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CSM_Security.Entities.Action", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("CSM_Security.Entities.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("EMail")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("CSM_Security.Entities.Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Features");
                });

            modelBuilder.Entity("CSM_Security.Entities.Permit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ActionShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Action");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<long>("FeatureShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Feature");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<long>("SolutionShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("Solution");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("FeatureShadow");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("SolutionShadow");

                    b.HasIndex("ActionShadow", "SolutionShadow", "FeatureShadow");

                    b.ToTable("Permits");
                });

            modelBuilder.Entity("CSM_Security.Entities.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("CSM_Security.Entities.Solution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sign")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Sign")
                        .IsUnique();

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("Profiles_Permits", b =>
                {
                    b.Property<long>("Permit")
                        .HasColumnType("bigint");

                    b.Property<long>("Profile")
                        .HasColumnType("bigint");

                    b.HasKey("Permit", "Profile");

                    b.HasIndex("Profile");

                    b.ToTable("Profiles_Permits");
                });

            modelBuilder.Entity("Accounts_Permits", b =>
                {
                    b.HasOne("CSM_Security.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("Account")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSM_Security.Entities.Permit", null)
                        .WithMany()
                        .HasForeignKey("Permit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounts_Profiles", b =>
                {
                    b.HasOne("CSM_Security.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("Account")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSM_Security.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("Profile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CSM_Security.Entities.Account", b =>
                {
                    b.HasOne("CSM_Security.Entities.Contact", "Contact")
                        .WithOne("Account")
                        .HasForeignKey("CSM_Security.Entities.Account", "ContactShadow")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("CSM_Security.Entities.Permit", b =>
                {
                    b.HasOne("CSM_Security.Entities.Action", "Action")
                        .WithMany("Permits")
                        .HasForeignKey("ActionShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSM_Security.Entities.Feature", "Feature")
                        .WithMany("Permits")
                        .HasForeignKey("FeatureShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSM_Security.Entities.Solution", "Solution")
                        .WithMany("Permits")
                        .HasForeignKey("SolutionShadow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Feature");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("Profiles_Permits", b =>
                {
                    b.HasOne("CSM_Security.Entities.Permit", null)
                        .WithMany()
                        .HasForeignKey("Permit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSM_Security.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("Profile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CSM_Security.Entities.Action", b =>
                {
                    b.Navigation("Permits");
                });

            modelBuilder.Entity("CSM_Security.Entities.Contact", b =>
                {
                    b.Navigation("Account");
                });

            modelBuilder.Entity("CSM_Security.Entities.Feature", b =>
                {
                    b.Navigation("Permits");
                });

            modelBuilder.Entity("CSM_Security.Entities.Solution", b =>
                {
                    b.Navigation("Permits");
                });
#pragma warning restore 612, 618
        }
    }
}
