<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>TWS_Customer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AppDesignerFolder>Configurations</AppDesignerFolder>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSM Foundation\CSM Foundation.csproj" />
    <ProjectReference Include="..\CSM Security\CSM Security.csproj" />
    <ProjectReference Include="..\TWS Business\TWS Business.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Configurations\solutions_configuration.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
