<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TWS_Customer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AppDesignerFolder>Configurations</AppDesignerFolder>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSM Security\CSM Security.csproj" />
    <ProjectReference Include="..\TWS Business\TWS Business.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="CSM.Database.Core" Version="4.4.0" />
    <PackageReference Include="CSM.Foundation.Core" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.2" />
	<PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Configurations\solutions_configuration.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="CSMS.Connection\development.connection.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="CSMS.Connection\quality.connection.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
